services:

  ollama:
    # image: ollama/ollama
    image: ollama/ollama:0.32.15
    volumes:
      - /mnt/my-space/1-ai-agents/1-models/1-ollama:/ollama
    container_name: ollama
    networks:
      - crm
    ports:
      - "11434:11434"
    stdin_open: true
    tty: true
    # devices:
      # - /dev/kfd
      # - /dev/dri
    # environment:
      # - OLLAMA_CONTEXT_LENGTH=200
      # - OLLAMA_VULKAN=1
      # - OLLAMA_NUM_PARALLEL=4

  tau-bench:
    build:
      context: .
      dockerfile: Dockerfile-taubench
    image: tau-bench
    container_name: tau-bench
    networks:
      - crm
    ports:
      - 8004:8004
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_BASE=ollama:11434
      - OPENAI_API_KEY=ollama
      - MODEL=qwen3:8b

  open-webui:
    build:
      context: /mnt/my-space/4-local-ai-crm/20-local-crm-ai-research/openwebui/
      dockerfile: /mnt/my-space/4-local-ai-crm/20-local-crm-ai-research/.docker/Dockerfile-openwebui
    image: openwebui
    container_name: openwebui
    networks:
      - crm
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434' 
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_MCP_SERVER=true'
      - 'MCP_ENABLE=true'
    # restart: unless-stopped

  mcp:
      build:
        context: /mnt/my-space/1-ai-agents/3-open-webui/mcpo
        dockerfile: /mnt/my-space/1-ai-agents/3-open-webui/mcpo/Dockerfile
      image: mcp
      volumes:
        - /home/allanmogley/Downloads/mcp.json:/app/config/config.json
      container_name: mcp
      tty: true
      stdin_open: true
      command:

        # - "mcpo"
        # - "--port"
        # - "8000"
        # - "--"
        # - "uvx"
        # - "mcp-server-time"
        # - "--local-timezone=Europe/Budapest"


        - mcpo
        - --port
        - "8001"
        # - "--"
        # - "uvx"
        - --server-type
        - streamable-http
        - --header
        - '{"Authorization": "Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjBjODg2OTBiLTgwMzItNGQ4OS05YzZmLTg2NzQzZGFiMzBjMSJ9.eyJzdWIiOiI1M2VhMjE4ZS03MzYxLTQ4N2YtODJjZC05YjdjMjcxODZjMWMiLCJ0eXBlIjoiQVBJX0tFWSIsIndvcmtzcGFjZUlkIjoiNTNlYTIxOGUtNzM2MS00ODdmLTgyY2QtOWI3YzI3MTg2YzFjIiwiaWF0IjoxNzg3NTEyODU0LCJleHAiOjQ5NDA5NDAwNTMsImp0aSI6IjMzYmYxYzAwLWQ4ZWEtNDMxMy05OTQzLTdkYWJmZTMwNDFkZiJ9.keK6e-vN_H3BpxiznmHfwvVM7---C7WSrVK0_gTUTsXhEyE109uDc2AoqSc9UdW2sp8R6kVoJQiestLnjdOXLg"}'
        - --
        - http://server:3000/mcp
      
      networks:
        - crm
      ports:
        - 8001:8000

networks:
  crm:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}